apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{cookiecutter.project_name}}
spec:
  minReadySeconds: 30
  replicas: 1
  revisionHistoryLimit: 2
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{cookiecutter.project_name}}
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "3000"
    spec:
      containers:
        - name: {{cookiecutter.project_name}}
          image: crodriguezanton/gshell-example-{{cookiecutter.project_name}}:latest
          ports:
          - containerPort: 3000
          resources:
            limits:
              cpu: 300m
            requests:
              cpu: 100m
        - name: esp
          image: gcr.io/endpoints-release/endpoints-runtime:1
          args: [
            "--http_port", "8080",
            "--backend", "127.0.0.1:3000",
            "--service", "{{cookiecutter.project_name}}.endpoints.oval-heuristic-236909.cloud.goog",
            "--rollout_strategy", "managed"
          ]
          ports:
          - containerPort: 8080
