apiVersion: v1
kind: Service
metadata:
  name: {{cookiecutter.project_name}}
  labels:
    app: {{cookiecutter.project_name}}
spec:
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 3000
  selector:
    app: {{cookiecutter.project_name}}
  type: LoadBalancer
